import pygame
map = '''
GGGGGGGGGGGGGGGGGGGGGGGGGGGXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
GGGGGGGGGGGGGGGGGGGGGGGGGGGXOOOOOOOXOOXXXXXXOOOOXOOOXOOOXOOOOXOOOXOOOOX
GGGGGGGGGGGGGGGGGGGGGGGGGGGXOOOOOOOX/|XXXXXXOOOOXOOOXOOOXOOOOXOOOXOOOOX
GGGGGGGGGGGGGGGGGGGGGGGGGGGXOOOOOOOX/|XXXXXXXDXXXOOOXOOOXXXDXXOOOXXXDXX
GGGGGGGGGGGGGGGGGGGGGGGGGGGXOOOOOOOX/|XXXXXXOOOODOOOXOOODOOOOXOOODOOOOX
GGGGGGGGGGGGGGGGGGGGGGGGGGGXXXDXXXXXDDXXXXXXXDXXXXXXXXXXXXXDXXXXXXXXDXX
GGGGGGGGGGGGGGGGGGGGGGGGGGGXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX
GGGGGGGGGGGGGGGGGGGGGGGGGGGXOCCCOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX
GGGGGGGGGGGGGGGGGGGGGGGGGGGXOCTTCOOOOOXXXXXXXDXXXXXXXXXXXXXDXXXXXXXXDXX
GGGGGGGGGGGGGGGGGGGGGGGGGGGXOCTTCOOOOOXOOOOXOOOODOOOXOOODOOOOXOOODOOOOX
GGGGGGGGGGGGGGGGGGGGGGGGGGGXOCTTCOOOOOXOOOOXXDXXXOOOXOOOXXXDXXOOOXXXDXX
GGGGGGGGGGGGGGGGGGGGGGGGGGGXOOOOOOOOOOXOOOOXOOOOXOOOXOOOXOOOOXOOOXOOOOX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXOOOOOOOOOODOOOOXOOOOXOOOXOOOXOOOOXOOOXOOOOX
XOOOOXOOOXOOOXOOOOXOOOXOOOOXXXXXXXOOOOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XOOOOXOOOXOOOXOOOOXOOOXOOOOXOOOOOXOOOOXGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
XXDXXXOOOXOOOXXXDXXOOOXXXDXXOOOOOXOOOOXGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
XOOOODOOOXOOODOOOOXOOODOOOOXDXXXXXOOOODRGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
XXDXXXXXXXXXXXXXDXXXXXXXXDXXOOOTTTOOOODRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODRRGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXGRGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
XXDXXXXXXXXXXXXXDXXXXXXXXDXXXXXXXDDXOOXGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
XOOOODOOOXOOODOOOOXOOODOOOOXXXXXX/|XOOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXDXXXOOOXOOOXXXDXXOOOXXXDXXXXXXX/|XOOXOOOOXOOOOXOOOXOOOXOOOOXOOOXOOOOX
XOOOOXOOOXOOOXOOOOXOOOXOOOOXXXXXX/|XOODOOOOXOOOOXOOOXOOOXOOOOXOOOXOOOOX
XOOOOXOOOXOOOXOOOOXOOOXOOOOXXXXXXOOXOOXOOOOXXDXXXOOOXOOOXXXDXXOOOXXXDXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOOXOOOOXOOOODOOOXOOODOOOOXOOODOOOOX
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGXOOXXXXXXXDXXXXXXXXXXXXXDXXXXXXXXDXX
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGXOOXXXXXXXDXXXXXXXXXXXXXDXXXXXXXXDXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOOXOOOOXOOOODOOOXOOODOOOOXOOODOOOOX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOOXOOOOXXDXXXOOOXOOOXXXDXXOOOXXXDXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOOXOOOOXOOOOXOOOXOOOXOOOOXOOOXOOOOX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOOXOOOOXOOOOXOOOXOOOXOOOOXOOOXOOOOX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXDDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
'''
pygame.init()
def draw_map():
    windowX = 781
    windowY = 700
    gameDisplay = pygame.display.set_mode([windowX, windowY])
    thing = map.split('\n')
    if thing[0] == '':
        del thing[0]
    if thing[-1] == '':
        del thing[-1]
    celly = int(windowY / len(thing))
    cellx = int(windowX / len(thing[0]))
    for i in range(len(thing)):
        for j in range(len(thing[0])):
            if thing[i][j] == 'X':
                pygame.draw.rect(gameDisplay, (255, 255, 255), (j*cellx, i*celly, cellx, celly))
            elif thing[i][j] == 'O':
                pygame.draw.rect(gameDisplay, (218,165,32), (j * cellx, i * celly, cellx, celly))
            elif thing[i][j] == 'D':
                pygame.draw.rect(gameDisplay, (165,42,42), (j * cellx, i * celly, cellx, celly))
            elif thing[i][j] == '/':
                pygame.draw.rect(gameDisplay, (112, 128, 144), (j * cellx, i * celly, cellx, celly))
            elif thing[i][j] == 'T':
                pygame.draw.rect(gameDisplay, (210, 180, 140), (j * cellx, i * celly, cellx, celly))
            elif thing[i][j] == 'C':
                pygame.draw.rect(gameDisplay, (188,143,143), (j * cellx, i * celly, cellx, celly))
            elif thing[i][j] == 'G':
                pygame.draw.rect(gameDisplay, (0, 255, 0), (j * cellx, i * celly, cellx, celly))
            elif thing[i][j] == 'R':
                pygame.draw.rect(gameDisplay, (128, 128, 128), (j * cellx, i * celly, cellx, celly))
    pygame.display.update()
